### ISSUE TITLE
Add convenience method for comparing `DebugUtilsMessageSeverityFlagEXT`s

### ISSUE THREAD

**Issue by Seelengrab** [JuliaGPU/Vulkan.jl#10]
Since these are arranged to be comparable via `>=` (at least the tutorial pretends that's the case), this would be useful and save some unwrapping. E.g. this

```
Base.isless(a::DebugUtilsMessageSeverityFlagEXT, b::DebugUtilsMessageSeverityFlagEXT) = isless(a.val, b.val)
```

does the job, unsure where/how this would be added. Just putting it into the namespace somewhere seems to work fine (as a hacky fix while I work through vulkan-tutorial.com, at least).

**Comment by serenity4** [comment]
Indeed, since they are basically integers they are comparable. We currently have `&`, `|` and `xor` defined on `BitMask`s (of which `DebugUtilsMessageSeverityFlagEXT` is a subtype) in [this file](https://github.com/JuliaGPU/Vulkan.jl/blob/c3ba789a356bb738687d89cca22ad83fa37452a7/src/prewrap/bitmasks.jl). We can add methods for `isless` and `isgreater`. Feel free to submit a PR with the proposed change for all `BitMask`s (you can get inspiration from the other operators).

**Comment by Seelengrab** [comment]
I think `isless` by itself should be enough, I think the rest is inferred with fallback definitions.
