### ISSUE TITLE
Cleanup

### ISSUE THREAD

**Issue by jeannekamikaze** [JuliaGPU/Vulkan.jl#30]
Hello,

I am new to Julia and it is not very clear to me how resources such as instances and logical devices should be destroyed with `Vulkan.jl`. Should we call, say, `destroy_device()`, or maybe `finalize()`?

Reading the [generated](https://raw.githubusercontent.com/JuliaGPU/Vulkan.jl/master/generated/linux.jl) code, it looks like resources are automatically associated with a destructor, but it is not entirely clear to me what the purpose of that is.

Thank you.

**Comment by serenity4** [comment]
Hi,
Finalizers are automatically setup so that you don't have to do anything yourself for cleanup. When there are no longer any program references to a handle, its finalizer will run and therefore call the corresponding Vulkan destructor function (e.g. `destroy_device`, mapped to its Vulkan counterpart `vkDestroyDevice` for devices).
If you want to free a `handle` early (and not wait for the finalizer to run by itself), you can call `finalize(handle)`. That way, the registered finalizer will run at this point, and not later.

I updated [the documentation](https://juliagpu.github.io/Vulkan.jl/dev/tutorial/types/#Automatic-finalization) to make it clearer, you can have a look for more information. If your problem was solved, then feel to close this issue.

**Comment by jeannekamikaze** [comment]
Thank you very much. I was going to ask about the order of destruction, but I see you took care of that too :)

Thank you.
