### ISSUE TITLE
[question] Recommended compiler from GLSL to SPIR-V

### ISSUE THREAD

**Issue by exaexa** [JuliaGPU/Vulkan.jl#33]
Hello,

first off, many thanks for writing this wrapper, it works so nicely. With completion and inline documentation, coding vulkan in REPL is just way happier experience than in other languages. This issue is more of a question and perhaps a request for documentation, and I understand that this is not a core concern for Vulkan wrapper libraries, but I gues it'd better be answered for the sake of library usefulness :]

Question: what is the easiest way to compile shaders to spir-v, say from a triple-quoted string literal with glsl directly to `Vector{Uint32}`?

Currently I'm just running the `glslangValidator` binary manually, but that's neither very safe, convenient, nor portable. If there is a good "reasonably portable" approach to call `glslang` or `shaderc` from julia? If there exists a recommendable way, mind if I send a PR that adds it to (say) a FAQ in the documentation? (Perhaps together with some of my other discoveries, mostly `unwrap`, and the Very Useful™ minimal compute example :] )

Thanks!

**Comment by serenity4** [comment]
Hi, thanks for the feedback!

You can run `glslangValidator` or `shaderc` as an external program from Julia (see [this section](https://docs.julialang.org/en/v1/manual/running-external-programs/) of the Julia documentation for more info). You can take some inspiration from [there](https://github.com/serenity4/VulkanShaders.jl/blob/master/src/compilation.jl#L16-L38); the repo is outdated and unmaintained, but you should be able to adapt the linked function to your needs. Note that you can directly use `glslangValidator` via the Artifact system (via `glslang_jll`, [see here](https://github.com/serenity4/VulkanShaders.jl/blob/master/src/VulkanShaders.jl#L13) to get the path to the binary from Julia).

Feel free to submit a PR to improve the docs if you want :) otherwise, I plan to have another pass at them along with other changes in the near future, so I'd gladly add a relevant section for shader compilation at the same time.

Out of curiosity, what was your discovery with `unwrap`? Is there a usage tip not covered [there](https://juliagpu.github.io/Vulkan.jl/dev/tutorial/error_handling/) that you found useful?

**Comment by exaexa** [comment]
Ah nice thanks a lot, I think glslang_jll would be the way to go. I'll try to put something together and write the documentation piece for new users.

Re `unwrap`, I was trying to reinvent the "minimal compute" example and spent some time realizing that `map_memory(device, ..., memory, ...)` should instead contain `..., unwrap(memory), ...`. Complete beginner-ish error caused by not RTFMing completely, and now that I see it, I should `unwrap` right away. I'll just post the complete example to the docs when I have it, hopefully it will save similar problems for others who read the docs as the last resort. :D

**Comment by serenity4** [comment]
Indeed, having that info in more places via examples and tutorials would definitely help. Not everybody goes through every section before starting to code! :)

**Comment by exaexa** [comment]
> Not everybody goes through every section before starting to code! :)

Yeah, 'tis Julia, you're supposed to [tab] through it towards the result. :D :D

Thanks for the info, I'll try to put something together ASAP.

**Comment by exaexa** [comment]
Solved by #34 :]
