### ISSUE TITLE
Intended Purpose of this Package Going Forward

### ISSUE THREAD

**Issue by weiameili** [JuliaGPU/Vulkan.jl#42]
Hi, while this is currently a WIP I was curious to know whether this Package when complete will serve as a safe wrapper around the Vulkan API, or will it also provide helper functions that will abstract away some of the tasks that are required when making a Vulkan application (like functions for image and buffer creation that automatically allocate and bind memory, other functions for memory management etc.)

And if it's the latter, has the package reached a point where work on such functionality can be started or will it be started at some point in the future.

**Comment by serenity4** [comment]
Hi, this package is only intended as a safe wrapper around the Vulkan API. While it might not sound like much, there's actually a ton of work required to do it properly and in an automated way. It is still currently considered a WIP simply because there hasn't been any major application that used it to confirm its validity at a large scale (that I know of at least), but bugs in corner cases are getting pretty rare nowadays.

Abstractions would have their place in a separate package. They would typically be lossy, as the Vulkan API was specifically made to be as simple as possible while retaining most of its expressiveness to provide ways to achieve maximal performance (which in great part accounts for its very large API surface that makes it so complex). The whole point of this package is to provide a way to interact with Vulkan without making any trade-offs, as trade-offs are usually use-case dependent. I find abstractions very hard to do well without knowing what the end application requires; for example, there are many ways to perform memory management, and a way that would work for all applications the same would probably not benefit much from using Vulkan. There are pieces that can be automated for common use cases of course, but advanced use cases would probably not be able to build from them, at which point such abstractions would not make much sense. I believe abstractions might typically reside in renderers or compute packages that accomplish specific goals, when the aim is clear. For example, for a renderer I'd typically like to have all my images and buffers known to a centralized data structure called a render graph, so I know exactly when and what my resources are used for to allow optimizations to be carried out with this information (there is [this WIP renderer](https://github.com/serenity4/Lava.jl) if you want to take a look).

It might be that certain renderers or compute libraries end up with using common abstractions or having common needs, in which case it would make a lot of sense to have abstraction packages, but I would not attempt to first try to build an abstraction library and then build an application.
