### ISSUE TITLE
Surfaces obtained from GLFW have to be converted & destroyed manually

### ISSUE THREAD

**Issue by Seelengrab** [JuliaGPU/Vulkan.jl#9]
Obtaining a surface from GLFW via `GLFW.CreateWindowSurface(instance, window)` have to be destroyed manually via a call to `destroy_surface_khr`. You also seem to have to acquire the correct type manually (via `SurfaceKHR(surface, instance, RefCounter(0))`) in the first place.

If they're not destroyed, Vulkan (rightfully so) complains about the instance being destroyed in spite of the surface not being destroyed yet. 

Not sure where/how this should be added.

**Comment by serenity4** [comment]
There is a (admittedly hidden) constructor for any handle type which allows you to register a destructor:

https://github.com/JuliaGPU/Vulkan.jl/blob/c3ba789a356bb738687d89cca22ad83fa37452a7/src/prewrap/handles.jl#L33-L36

The following should solve your problem:
```julia
surface_ptr = GLFW.CreateWindowSurface(instance, window)
surface = SurfaceKHR(surface_ptr, x -> destroy_surface_khr(instance, x), instance)
```

It sets up the refcount for you (and must be initialized to 1, not 0, since the finalizer will decrement it and *then* try to destroy the handle if refcount reaches 0), including incrementing that of the parent handle (the instance) and decrementing it once the surface is destroyed.

Please let me know if that fixes the issue. If so, I'll add this to the documentation.

**Comment by Seelengrab** [comment]
Yes, that seems to work! 

Could this be exposed as `SurfaceKHR(surface, instance)`, with that method setting up the destructor automatically?

**Comment by serenity4** [comment]
Great!

I am not sure that we should expose such a constructor. There may be cases where an external library would free the handle, in which case we'd need a `SurfaceKHR` to work with Vulkan.jl but without freeing it at the end (same for all other handles), where you would typically pass in `Base.identity` as a destructor. Also handle destructors such as `destroy_surface_khr` expose the keyword argument `allocator=C_NULL`, which would need to be reexposed for all constructors. I believe it is better to just document the case you encountered and have the destructor explicitly passed in, since it should happen only occasionally.

**Comment by Seelengrab** [comment]
Agreed, it's very specific to GLFW, it seems.
